<a href="https://colab.research.google.com/github/Nakib-Nasrullah/Research-Skill/blob/main/Numpy_%26_Pandas_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy pandas matplotlib

In [2]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')

print("NumPy version:", np.__version__)
print("Pandas.version:", pd.__version__)

NumPy version: 2.0.2
Pandas.version: 2.2.2


In [3]:
#Creating Numpy array
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])
print("1D array:",arr1)
print("2D array:",arr2)
print("Array shape:",arr1.shape)
print("Array shape:",arr2.shape)
print("Array dtatype:", arr1.dtype)

1D array: [1 2 3 4 5 6]
2D array: [[1 2 3]
 [4 5 6]]
Array shape: (6,)
Array shape: (2, 3)
Array dtatype: int64


In [4]:
#Differwnts ways to create arrays
zeros_array = np.zeros((3,4))
ones_array = np.ones((2,3))
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 5)
print("Zeros array: \n", zeros_array)
print("Ones array: \n", ones_array)
print("Range array: \n", range_array)
print("Linspace array: \n",linspace_array)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Range array: 
 [0 2 4 6 8]
Linspace array: 
 [0.   0.25 0.5  0.75 1.  ]


In [6]:
#Mathematical operations on arrays
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

#Element-wise operations
print("Addition:", a+b)
print("Multiplication:", a*b)
print("Power:", a**2)
print("Square root:", np.sqrt(a))
print("Square root:", np.sqrt(b))

Addition: [ 3  5  7  9 11]
Multiplication: [ 2  6 12 20 30]
Power: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
