<a href="https://colab.research.google.com/github/Nakib-Nasrullah/Research-Skill/blob/main/Numpy_%26_Pandas_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy pandas matplotlib

In [7]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')

print("NumPy version:", np.__version__)
print("Pandas.version:", pd.__version__)

NumPy version: 2.0.2
Pandas.version: 2.2.2


In [8]:
#Creating Numpy array
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])
print("1D array:",arr1)
print("2D array:",arr2)
print("Array shape:",arr1.shape)
print("Array shape:",arr2.shape)
print("Array dtatype:", arr1.dtype)

1D array: [1 2 3 4 5 6]
2D array: [[1 2 3]
 [4 5 6]]
Array shape: (6,)
Array shape: (2, 3)
Array dtatype: int64


In [9]:
#Differwnts ways to create arrays
zeros_array = np.zeros((3,4))
ones_array = np.ones((2,3))
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 5)
print("Zeros array: \n", zeros_array)
print("Ones array: \n", ones_array)
print("Range array: \n", range_array)
print("Linspace array: \n",linspace_array)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Range array: 
 [0 2 4 6 8]
Linspace array: 
 [0.   0.25 0.5  0.75 1.  ]


In [10]:
#Mathematical operations on arrays
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

#Element-wise operations
print("Addition:", a+b)
print("Multiplication:", a*b)
print("Power:", a**2)
print("Square root:", np.sqrt(a))
print("Square root:", np.sqrt(b))

Addition: [ 3  5  7  9 11]
Multiplication: [ 2  6 12 20 30]
Power: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [11]:
# Statistical operation
print("Mean:", np.mean(a))
print("Mean:", np.mean(b))
print("Standard deviation:", np.std(a)) #Standerd deviations => Average value থেকে কতটুকু বিচ্যুতি আছে!!
print("Standard deviation:", np.std(b))
print("Min:", np.min(a))
print("Min:", np.min(b))
print("Max:", np.max(a))
print("Max:", np.max(b))

Mean: 3.0
Mean: 4.0
Standard deviation: 1.4142135623730951
Standard deviation: 1.4142135623730951
Min: 1
Min: 2
Max: 5
Max: 6


In [12]:
 #Broadcusting example
 matrix = np.array([[1,2,3],[4,5,6]])
 vector = np.array([10,20,30])
 result = matrix + vector
 print("Broadcusting result:\n", result)

Broadcusting result:
 [[11 22 33]
 [14 25 36]]


In [16]:
arr = np.array([10,20,30,40,50,60])

#Indexing
print("Element at index 2:", arr[2])
print("Element at index 4:", arr[5])
#Slicing
print("Sliced array (from index 1 to 3):", arr[1:4])

# 2D array slicing
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Sliced 2D array (first two rows):\n", arr_2d[:2])
print("Sliced 2D array (first two column):\n", arr_2d[:,:2])

Element at index 2: 30
Element at index 4: 60
Sliced array (from index 1 to 3): [20 30 40]
Sliced 2D array (first two rows):
 [[1 2 3]
 [4 5 6]]
Sliced 2D array (first two column):
 [[1 2]
 [4 5]
 [7 8]]


In [19]:
# Pandas
data = {'Name': ['Alice','Bob', 'charlie'],
        'Age': [24, 26, 30],
        'City': ['New York' , 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)  # pd.DataFrame() is a pandas defoult library
print("DataFrame:\n",df)

DataFrame:
       Name  Age         City
0    Alice   24     New York
1      Bob   26  Los Angeles
2  charlie   30      Chicago


In [23]:
# Numpy,Pandas and seborn are use for numaric calculation.
# Basic Dataframe information
print("\nDataFrame info:")
print(df.info())

print("\nDataFrame Description:\n")
print(df.describe())


DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

DataFrame Description:

             Age
count   3.000000
mean   26.666667
std     3.055050
min    24.000000
25%    25.000000
50%    26.000000
75%    28.000000
max    30.000000


In [31]:
print("\nDataFrame Shape:", df.shape)
print("\nColumn names:", df.columns.tolist())
# Display first 5 rows
print("\nFirst 5 rows of the dataset:")
print(df.head())
# Display last 5 rows
print("\nLast 5 rows of the dataset:")
print(df.tail())


DataFrame Shape: (3, 3)

Column names: ['Name', 'Age', 'City']

First 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   26  Los Angeles
2  charlie   30      Chicago

Last 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   26  Los Angeles
2  charlie   30      Chicago
