<a href="https://colab.research.google.com/github/Nakib-Nasrullah/Research-Skill/blob/main/Numpy_%26_Pandas_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy pandas matplotlib

In [2]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')

print("NumPy version:", np.__version__)
print("Pandas.version:", pd.__version__)

NumPy version: 2.0.2
Pandas.version: 2.2.2


In [3]:
#Creating Numpy array
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])
print("1D array:",arr1)
print("2D array:",arr2)
print("Array shape:",arr1.shape)
print("Array shape:",arr2.shape)
print("Array dtatype:", arr1.dtype)

1D array: [1 2 3 4 5 6]
2D array: [[1 2 3]
 [4 5 6]]
Array shape: (6,)
Array shape: (2, 3)
Array dtatype: int64


In [4]:
#Differwnts ways to create arrays
zeros_array = np.zeros((3,4))
ones_array = np.ones((2,3))
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 5)
print("Zeros array: \n", zeros_array)
print("Ones array: \n", ones_array)
print("Range array: \n", range_array)
print("Linspace array: \n",linspace_array)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Range array: 
 [0 2 4 6 8]
Linspace array: 
 [0.   0.25 0.5  0.75 1.  ]


In [5]:
#Mathematical operations on arrays
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

#Element-wise operations
print("Addition:", a+b)
print("Multiplication:", a*b)
print("Power:", a**2)
print("Square root:", np.sqrt(a))
print("Square root:", np.sqrt(b))

Addition: [ 3  5  7  9 11]
Multiplication: [ 2  6 12 20 30]
Power: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [6]:
# Statistical operation
print("Mean:", np.mean(a))
print("Mean:", np.mean(b))
print("Standard deviation:", np.std(a)) #Standerd deviations => Average value থেকে কতটুকু বিচ্যুতি আছে!!
print("Standard deviation:", np.std(b))
print("Min:", np.min(a))
print("Min:", np.min(b))
print("Max:", np.max(a))
print("Max:", np.max(b))

Mean: 3.0
Mean: 4.0
Standard deviation: 1.4142135623730951
Standard deviation: 1.4142135623730951
Min: 1
Min: 2
Max: 5
Max: 6


In [7]:
 #Broadcusting example
 matrix = np.array([[1,2,3],[4,5,6]])
 vector = np.array([10,20,30])
 result = matrix + vector
 print("Broadcusting result:\n", result)

Broadcusting result:
 [[11 22 33]
 [14 25 36]]


In [8]:
arr = np.array([10,20,30,40,50,60])

#Indexing
print("Element at index 2:", arr[2])
print("Element at index 4:", arr[5])
#Slicing
print("Sliced array (from index 1 to 3):", arr[1:4])

# 2D array slicing
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Sliced 2D array (first two rows):\n", arr_2d[:2])
print("Sliced 2D array (first two column):\n", arr_2d[:,:2])

Element at index 2: 30
Element at index 4: 60
Sliced array (from index 1 to 3): [20 30 40]
Sliced 2D array (first two rows):
 [[1 2 3]
 [4 5 6]]
Sliced 2D array (first two column):
 [[1 2]
 [4 5]
 [7 8]]


In [9]:
# Pandas
data = {'Name': ['Alice','Bob', 'charlie'],
        'Age': [24, 26, 30],
        'City': ['New York' , 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)  # pd.DataFrame() is a pandas defoult library
print("DataFrame:\n",df)

DataFrame:
       Name  Age         City
0    Alice   24     New York
1      Bob   26  Los Angeles
2  charlie   30      Chicago


In [10]:
# Numpy,Pandas and seborn are use for numaric calculation.
# Basic Dataframe information
print("\nDataFrame info:")
print(df.info())

print("\nDataFrame Description:\n")
print(df.describe())


DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

DataFrame Description:

             Age
count   3.000000
mean   26.666667
std     3.055050
min    24.000000
25%    25.000000
50%    26.000000
75%    28.000000
max    30.000000


In [11]:
print("\nDataFrame Shape:", df.shape)
print("\nColumn names:", df.columns.tolist())
# Display first 5 rows
print("\nFirst 5 rows of the dataset:")
print(df.head())
# Display last 5 rows
print("\nLast 5 rows of the dataset:")
print(df.tail())


DataFrame Shape: (3, 3)

Column names: ['Name', 'Age', 'City']

First 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   26  Los Angeles
2  charlie   30      Chicago

Last 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   26  Los Angeles
2  charlie   30      Chicago


In [12]:
# Check data types
print("\nData Types:")
print(df.dtypes)


Data Types:
Name    object
Age      int64
City    object
dtype: object


In [13]:
# Accessing a single column
print("Names column:\n", df['Name'])

# Accessing multiple columns
print("\nName and Age columns:\n", df[['Name', 'Age']])

Names column:
 0      Alice
1        Bob
2    charlie
Name: Name, dtype: object

Name and Age columns:
       Name  Age
0    Alice   24
1      Bob   26
2  charlie   30


In [14]:
# Convert Numpy array to DataFrame
np_array = np.random.randn(5, 3)
df_from_array = pd.DataFrame(np_array, columns=['A', 'B', 'C'])
print("DataFrame from NumPy array: ")
print(df_from_array)


DataFrame from NumPy array: 
          A         B         C
0 -1.088877  0.532112 -0.226778
1 -0.622737  0.356932 -1.551731
2 -0.636041  0.605595  0.978626
3 -0.391206 -0.670683 -1.325414
4  2.312821  0.306000 -0.512484


In [15]:
# Convert Numpy array to DataFrame
np_array2 = np.random.randn(5, 4)
df_from_array2 = pd.DataFrame(np_array2, columns=['A', 'B', 'C', 'D'])
print("DataFrame from NumPy array2: ")
print(df_from_array2)

DataFrame from NumPy array2: 
          A         B         C         D
0  0.356790  0.123266 -1.620201  0.124332
1  1.881130 -0.230521  0.341641 -0.363845
2 -0.922022  0.719010  0.788679  0.884741
3  0.735264  0.721646  1.289188  0.783162
4  0.601197 -1.030631  2.284197  2.119219


In [16]:
# Creating asample sales data

sales_data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 120, 110, 180, 190, 140],
    'Quantity': [10, 15, 20, 12, 11, 19, 14, 20]
}
sales_df = pd.DataFrame(sales_data)
print("Sales DataFrame: ")
print(sales_df)

Sales DataFrame: 
  Region Product  Sales  Quantity
0  North       A    100        10
1  South       A    150        15
2   East       B    200        20
3   West       B    120        12
4  North       A    110        11
5  South       B    180        19
6   East       A    190        14
7   West       B    140        20


In [17]:
# Group by operation 1.sum 2.maximum 3.minimum 4.Avarage 5.Mode
region_sales = sales_df.groupby('Region')['Sales'].sum()
region_sales_max = sales_df.groupby('Region')['Sales'].max()
print("\nSales by Region: ")
print(region_sales)
print("\nMax sales by region: ")
print(region_sales_max)


Sales by Region: 
Region
East     390
North    210
South    330
West     260
Name: Sales, dtype: int64

Max sales by region: 
Region
East     200
North    110
South    180
West     140
Name: Sales, dtype: int64


In [29]:
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [30]:
file_path = '/content/drive/MyDrive/Datasets/diabetes.csv'
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThikness','Insuline','BMI', 'DiabetesPedigreeFuntion', 'Age', 'Outcome']
df = pd.read_csv(file_path)
print("Deraset loaded sucessfully. Shape:", df.shape)

Deraset loaded sucessfully. Shape: (768, 9)


In [32]:
data_array = df.values
print("Numpy array shape:", data_array.shape)
print("Data type:", data_array.dtype)

Numpy array shape: (768, 9)
Data type: float64
